#!/bin/bash

# dependencies:

# TODO: This should identify the location of the install script,
#       not the location from which the user calls the script.
PROJDIR=$(pwd)

# root home dir
ln -s $PROJDIR/bashrc ~/.bashrc
ln -s $PROJDIR/xinitrc ~/.xinitrc
ln -s $PROJDIR/xprofile ~/.xprofile
ln -s $PROJDIR/Xresources ~/.Xresources
ln -s $PROJDIR/Xresources.d ~/.Xresources.d
ln -s $PROJDIR/inputrc ~/.inputrc

# pacaur
ln -s $PROJDIR/config/pacaur ~/.config/pacaur

ln -s $PROJDIR/gnupg/gpg-agent.conf ~/.gnupg/gpg-agent.conf
ln -s $PROJDIR/gnupg/dirmngr.conf ~/.gnupg/dirmngr.conf

# gnome swapcaps (TODO: can this be removed since the line is in .xprofile?)
mkdir -p ~/.config/autostart
ln -s $PROJDIR/config/autostart/swapcaps.desktop ~/.config/autostart/swapcaps.desktop
