#!/bin/bash

# dependencies:

# TODO: This should identify the location of the install script,
#       not the location from which the user calls the script.
PROJDIR=$(pwd)

# root home dir
ln -s $PROJDIR/bashrc ~/.bashrc
ln -s $PROJDIR/xinitrc ~/.xinitrc
ln -s $PROJDIR/xprofile ~/.xprofile
ln -s $PROJDIR/Xresources ~/.Xresources
ln -s $PROJDIR/Xresources.d ~/.Xresources.d

ln -s $PROJDIR/gnupg/gpg-agent.conf ~/.gnupg/gpg-agent.conf
ln -s $PROJDIR/gnupg/dirmngr.conf ~/.gnupg/dirmngr.conf

# gnome swapcaps
# TODO: Can the autostart and xprofile pieces be removed now that the gsettings is in place?
mkdir -p ~/.config/autostart
ln -s $PROJDIR/config/autostart/swapcaps.desktop ~/.config/autostart/swapcaps.desktop

gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:swapcaps']"
dconf load /org/gnome/terminal/ < gnome-terminal-config
