#!/bin/bash

# dependencies:

# TODO: This should identify the location of the install script,
#       not the location from which the user calls the script.
PROJDIR=$(pwd)

# root home dir
ln -s $PROJDIR/bashrc ~/.bashrc
ln -s $PROJDIR/xinitrc ~/.xinitrc
ln -s $PROJDIR/xprofile ~/.xprofile
ln -s $PROJDIR/Xresources ~/.Xresources
ln -s $PROJDIR/Xresources.d ~/.Xresources.d
ln -s $PROJDIR/yaourtrc ~/.yaourtrc

# systemctl doesn't like symlinked service files
mkdir -p ~/.config/systemd/user
cp $PROJDIR/config/systemd/user/emacs.service ~/.config/systemd/user/emacs.service
systemctl --user enable emacs
systemctl --user start emacs

# bspwm
ln -s $PROJDIR/config/bspwm ~/.config/bspwm
ln -s $PROJDIR/config/sxhkd ~/.config/sxhkd

# pacaur
ln -s $PROJDIR/config/pacaur ~/.config/pacaur

# gnome swapcaps (TODO: can this be removed since the line is in .xprofile?)
mkdir -p ~/.config/autostart
ln -s $PROJDIR/config/autostart/swapcaps.desktop ~/.config/autostart/swapcaps.desktop
