#!/bin/bash

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

# load basic configuration for the panel (dimensions, colors, fonts)
. panel_config
. panel_colors # to define BG & FG colors

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# make room for the panel
bspc config top_padding $((PANEL_HEIGHT+WINDOW_GAP))

# store data to send to the panel
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

# start the panel
cat "$PANEL_FIFO" | panel_bar | \
    lemonbar -g $((PANEL_WIDTH))x$PANEL_HEIGHT+$PANEL_X_OFF+$WINDOW_GAP \
             -f "$PANEL_FONT_FAMILY" -F "$COLOR_FG" -B "$COLOR_BG" &

wait
