#!/bin/bash

# user-modifiable parameters
export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=24
export PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-iso10646-1"

# grab the monitor width, and calculate the panel dimensions/offsets
CUR_MON_WIDTH=$(bspc query -T -m $i | grep -oE "[0-9]{2,6}" | head -n 1)

export PANEL_WIDTH=$((CUR_MON_WIDTH-WINDOW_GAP-WINDOW_GAP))
export PANEL_X_OFF=$WINDOW_GAP

